### ISSUE TITLE
feat: arm64 libs

### ISSUE THREAD

**Issue by davidgiga1993** [DerekCook/CoreMidi4J#46] opened 2023-05-09 11:48 UTC
Would it be possible to package the shared libs also for arm64? Currently this lib can't be used in conjunction with M1 native java apps.

**Comment by brunchboy** [comment] 2023-05-09 13:11
Do you have a proposal of how that could be done? A pull request would be welcome if you are building it successfully and can get it to build in Github Actions. Unfortunately, as far as I can tell, Github macOS ARM runners are still not released, and seem currently to be scheduled for Q4 of 2023 (and it keeps slipping). They may be in public beta, however, so if you have time to research this further a contribution would be welcome.

I recently moved to an M2 macBook, though, and this seems to work fine in Rosetta, so I don’t see any significant advantage that would be offered by a native arm64 library. It’s not as though CoreMidi4J does a lot of computation?

**Comment by git-moss** [comment] 2023-05-10 11:38
You simply need to buid a universal binary which contains both the x64 and ARM version. You can build it on both platforms. Therefore, there should be no change necessary to your GitHub action.
I haven't tested (don't have a Mac in reach this week) but it should be enough to add the ARM architecture to your XCode project.

**Comment by brunchboy** [comment] 2023-05-10 15:03
Ah, that sounds great, and we’d definitely welcome a PR along those lines! Otherwise, one of us will likely eventually get to it, but a PR would definitely speed things up. I don’t know about Derek, but I don’t live in Xcode these days, it’s probably been a few years since I used it.

**Comment by git-moss** [comment] 2023-05-15 05:59
I had a quick look at it yesterday. Turns out your dynlib in 1.6 is already a universal binary :-)

**Comment by brunchboy** [comment] 2023-05-15 15:27
Oh, thank you, Jürgen! I had thought so, but @davidgiga1993’s issue gave me doubt. David, your problem must be caused by something else, could you dig more deeply and let us know what is actually happening? Otherwise I will close this issue.

**Comment by DerekCook** [comment] 2023-05-21 08:49
Hi, late to the party as usual due to an insane workload, but have been following the conversation and I thought we had built a universal binary. 

As this has been confirmed, I will close this issue. Happy to reopen if we need to.

**Closed as completed by DerekCook** 2023-05-21 08:49 UTC
