### ISSUE TITLE
Java runtime does not terminate if NotificationListener is registered

### ISSUE THREAD

**Issue by DerekCook** [DerekCook/CoreMidi4J#9] opened 2016-01-30 11:16 UTC
As the title says. If you register to listen for environment changes then when you exit your application the Java runtime does not terminate.

We are currently not sure of the cause of this, but it's likely to be a thread hanging around somewhere.

The workaround is to call System.exit() when you exit your application.

**Comment by brunchboy** [comment] 2017-05-13 22:39
@DerekCook, I can’t reproduce this problem, and I wanted to try to see if we could fix it before the 1.0 release. Are you sure there wasn’t something else going on in your program when this came up? Did you ever find a minimal case where you could reproduce this with just CoreMidi4J and a test class? If not, perhaps we can close the issue?

**Comment by brunchboy** [comment] 2017-05-13 23:11
I take that back, there was a `System.exit(0);` call in the example code I was using without realizing it. I can totally reproduce this. How very weird.

**Comment by brunchboy** [comment] 2017-05-14 01:50
Ok, I have dug a bit deeper, and the problem is not precisely as specified here (which is good, because studying the `watchForMidiChanges()` code made it seem highly implausible as the culprit).

Whether or not you have registered a notification listener, the runtime will terminate just fine if no environment changes have occurred since startup, and will fail to terminate if an environment change has occurred. I am looking on the native side now to see how we deliver the notifications. I am hoping it will be as simple as marking a thread we are creating as a daemon thread.

**Comment by brunchboy** [comment] 2017-05-14 01:57
Ok, there is rather a smoking gun in the [source code](https://github.com/DerekCook/CoreMidi4J/blob/master/CoreMIDI4J/Native/CoreMidi4J/CoreMidiClient.cpp#L80-L81):

```java
// TODO Calling this function crashes the JVM!!!
//			callbackParameters->jvm->DetachCurrentThread();
```

I am investigating what we need to do to safely perform this operation.

**Comment by brunchboy** [comment] 2017-05-14 02:19
Further research reveals that it is not a good idea to try to attach and detach a thread like this; the thread should be detached only when it is about to exit,. However, [the JNI documentation](http://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/invocation.html) mentions another method that looks like it will do exactly what we need, `AttachCurrentThreadAsDaemon`. I am giving that a try.

**Comment by brunchboy** [comment] 2017-05-14 02:26
All right! Making that change resolves this issue. You no longer need to call `System.exit()` even if the MIDI environment has changed while your process is running (and even if you have registered for, and received, environment change notifications).

**Closed as completed** 2017-05-14 02:46 UTC
Labels: bug

**Comment by mrlimbic** [comment] 2018-11-23 18:22
I have this same issue. Are you sure it is fixed in 1.1?

VM doesn't shut down because two non daemon midi threads are still running even though I closed the two devices I opened.

This is one of them.. (I suspended it to take a look at the stack)

Thread [Java Sound MidiInDevice Thread] (Suspended)	
	MidiInDevice.nGetMessages(long) line: not available [native method]	
	MidiInDevice.run() line: 140 [local variables unavailable]	
	Thread.run() line: 748 [local variables unavailable]

**Comment by brunchboy** [comment] 2018-11-23 18:36
Those don’t appear to be CoreMIDI4J methods, so it looks like your problem may be with Oracle code.

**Comment by mrlimbic** [comment] 2018-11-23 18:45
Weirdly it didn't do this before I switched to coremidi4j (when I discovered the sysex messages were not getting through). Could there be something not released that causes oracle code to think it should continue?

**Comment by brunchboy** [comment] 2018-11-23 21:17
I can’t speculate on what might be happening without much more information. What leads you to believe the thread you showed above was the non-daemon thread which is keeping the JVM running? Are you certain you did not create any other non-daemon threads? Or any other library you are using? You’ll want to examine the full thread dump.

**Comment by brunchboy** [comment] 2018-11-23 21:35
Also, it’s possible you have found a new issue with CoreMIDI4J, of course. Unfortunately I am unlikely to have time to help look into it for many weeks, my other projects are under huge efforts. If you figure anything out, though, we’d love the details or even a pull request!
