### ISSUE TITLE
Failure building application - ini_md.h can't be found.

### ISSUE THREAD

**Issue by BradleyRoss** [DerekCook/CoreMidi4J#20] opened 2017-06-18 21:28 UTC
I just tried to build the CoreMidi4J application, and received an error message.  The StackOverflow item at https://stackoverflow.com/questions/7212982/jni-cannot-open-include-file-jni-md-h appears to be related since part of the log indicated problems with jni_md.h not being found.

***  ***
Edit:
The error occurred when running    mvn >log.txt  compile javadoc:javadoc package
When I ran     mvn package   , I didn't get the error message.
I followed this with 
mvn compile
mvn javadoc:aggregate
mvn package

with each phase as a separate command line, and it looks okay.  Does the javadoc have to be run as a separate step?
***  ***
/CoreMidi4J/CoreMIDI4J/Native/CoreMidi4J/build/CoreMidi4J.build/Release/CoreMidi4J.build/Objects-normal/x86_64/CoreMidiOutputPort.o
In file included from /Users/bradleyross/Development2016/Git2016/Master/CoreMidi4J/CoreMIDI4J/Native/CoreMidi4J/CoreMidiOutputPort.cpp:17:
In file included from /Users/bradleyross/Development2016/Git2016/Master/CoreMidi4J/CoreMIDI4J/Native/CoreMidi4J/CoreMidiOutputPort.h:20:
In file included from /Users/bradleyross/Development2016/Git2016/Master/CoreMidi4J/CoreMIDI4J/Native/CoreMidi4J/CoreMidi4J.h:2:
java_home/include/jni.h:45:10: fatal error: 'jni_md.h' file not found
#include "jni_md.h"
         ^

I was just curious if anybody had seen this before.

[log.txt](https://github.com/DerekCook/CoreMidi4J/files/1083394/log.txt)

**Comment by brunchboy** [comment] 2017-06-19 01:21
I had not seen that before. I looked at your log, and saw no problems in there. This build is more complex than anything else I have ever tried to do with Maven (frankly, I try to avoid Maven whenever I can), and this combination of Maven plus Xcode is just fraught with peril. I was amazed when I got it to work at all. So it may be that you need to do the main build before you can build the javadoc. If you can figure out a way to fix that, a pull request would be welcome.

**Comment by BradleyRoss** [comment] 2017-08-14 01:07
The problem is the order in which some of the tasks are being specified in the POM.  It was installing some of the files in the wrong order during the initial installation with regard to XCode.  Let me dig up my notes on this.  Part of the problem is that javah really shouldn't be in the build procedure.  javah creates some C header files and should be identical on each iteration.  If they do change, you have to change the rest of the C code.

See https://github.com/BradleyRoss/CoreMidi4J/blob/master/CoreMIDI4J/pom.xml for some of my comments.

**Comment by brunchboy** [comment] 2017-08-16 19:07
Hey, sorry I have been too busy with my real job to comment on this, but I am wondering why you closed this?

I do quickly want to say that `javah` indeed must be part of the build procedure. In order for people to be able to work with the library from source, especially if they are Clojure-oriented people, they need to be able to check out a copy of the repository, and with a single `mvn package` create the jar file, which contains the native library, so the C header files created by `javah` need to be created.

**Comment by BradleyRoss** [comment] 2017-08-17 21:08
I'm reopening the issue.

However, I feel that the code created by javah should be placed explicitly in the XCode code base.  Changing the header files means that the implementation code has to be rewritten.  The file CoreMidi4J.h is already apparently included in the XCode directory, so running javah in the build simply generates a file that is identical to what is already there.  If it produces a file that is different, the application fails because the implementation will no longer match the header file.  There should also be a note in the Java source files that changes to the methods marked as Native will require changes to be made to the source files.

I can see a reason for including the XCode build step since it is possible that the software and libraries used by XCode can change over time.  However, the CoreMidi4J.h file should never change.

**Comment by DerekCook** [comment] 2017-08-17 21:45
Not true. It could change if we change JNI method signatures for some reason. E.g. This request for CoreMidiDevices to provide additional info.

**Comment by brunchboy** [comment] 2017-08-17 21:48
Precisely. It has done that multiple times as we evolved and extended the library, and having a manual step that can be forgotten during the build process is a recipe for frustration and wasted time.

**Comment by brunchboy** [comment] 2017-08-17 22:05
Another way to think about it: If we change the JNI signatures and this requires the C++ implementation to change, we would rather find out about it right away during the build process, than with a crash at runtime because of a linkage error. And it’s no different than the fact that changing a Java interface in one file could require changes to the implementation in another Java file… the fact that these are two different languages, built by two different compilers, does add complexity, but they are still part of the same project, so changes in any one place need to be accommodated throughout the project as they happen.

**Comment by DerekCook** [comment] 2017-08-21 19:48
As part of getting ready to make some changes, as I have not done much building since James did the Maven work, I followed James's instructions to get Maven up and running (I normally avoid it), and did not encounter this problem.

**Comment by DerekCook** [comment] 2017-09-17 08:51
Hi

I'm closing this issue, as in the last month or so of working on CoreMIDI4J I have been using the build script with no issues, and @BradleyRoss has not added any additional info to allow us to replicate the info, and the reason for reopening the issue is also not related, and is expected behaviour. 

If you wish to reopen this with a replicable case to allow us to investigate then please do so.

**Closed as completed by DerekCook** 2017-09-17 08:51 UTC
