### ISSUE TITLE
Hang on MidiSystem.getMidiDeviceInfo()

### ISSUE THREAD

**Issue by SMerrony** [DerekCook/CoreMidi4J#10] opened 2016-01-31 12:11 UTC
Using JRE version 1.8.0_71 on OS X version 10.11.3 and having installed CoreMidi4J 0.4 I am getting a hang on the above method.

I'm trying to use CoreMidi4J to get the new https://github.com/SMerrony/EWItool2 working on OS X as it needs SysEx messages to work.

Please let me know if you need more info to diagnose the problem.

Thanks.

**Comment by brunchboy** [comment] 2016-01-31 19:04
Ouch, that sounds unfortunate. I am stuck on OS X 10.10 for a while yet as there are a couple of pieces of DJ equipment and software I use that are not yet compatible with 10.11, so I am of limited help here. Perhaps @DerekCook has been able to upgrade? In the mean time, if you could get a Java thread dump when it is hung, perhaps that could reveal something?

**Comment by SMerrony** [comment] 2016-01-31 19:40
Thanks for getting back to me so quickly.  Attached is a thread dump...
[thread_dump_1.txt](https://github.com/DerekCook/CoreMidi4J/files/111480/thread_dump_1.txt)

**Comment by DerekCook** [comment] 2016-01-31 20:38
Hi, my x.factory Librarians appear to be working OK with CoreMIDI4J on OSX 10.11.3 on JRE 8u51 (1.8.0_51)

I'm now going to be away for a few days on business, but once I am back (Wed evening onwards), I will grab the latest JDK 8 as soon as I can, check it out and report back.

PS: good to see another Wind Synth User. I have a WX5 and VL in my EX5 and PLG150-VL (in a Motif Rack ES). I am not very good at playing it yet, mind! Never seem to find the time to sit down with it.

**Comment by brunchboy** [comment] 2016-01-31 21:18
Thanks for the thread dump. That makes it look like things are getting gummed up in the native method `createClient`. That’s a part of the system that I know little about so far, so it will be best to wait until Derek has time to get back and ponder it. I also wonder if we are running into some sort of issue due to interactions with JavaFX, since the application you are using seems to use that as its framework, and on the call stack I see that there is a lock being held on a security manager… I wonder if that is giving us trouble when we try calling back into the JVM to cache information about the a callback method we will be using? But now I am just making things up—as I said, Derek will be much better placed to help investigate this once he has time. We may need to send you an instrumented version of the native library to dig deeper into where exactly it is getting stuck.

**Comment by DerekCook** [comment] 2016-02-05 11:51
I have JRE 8 U71 Installed on my Mac and in plain old Java, my an.factory librarian is working fine with CoreMIDI4J with no reported exceptions. So I suspect it is probably a JavaFX specific issue, and I know nothing about it - have never used it. Are you a developer who can help investigate and fix?

**Comment by SMerrony** [comment] 2016-02-06 09:03
I'm not suprised that JavaFX is triggering the issue.  I can help investigate (as a user of CoreMidi4J) but I don't know about fixing - I'm not a Mac person...  Attached is a minimal demonstration of the hang.  If you comment out the call to getMidiDeviceInfo() the program works normally.  The program works fine either way on both Windows and various Linuxes.
[FXmidiTest1.java.txt](https://github.com/DerekCook/CoreMidi4J/files/120202/FXmidiTest1.java.txt)

**Comment by DerekCook** [comment] 2016-02-06 10:51
OK. I'll try and look at the example when I get five minutes, but it may be a few weeks, as I need to prioritise the next release of my x.factory Librarians.

Dumb question: Do you get the exception if CoreMIDI4J is not installed? Obviously external transfers will not work, but it will be interesting to see if "normal" Java MIDI is OK, and if noting else it will rule that out.

**Comment by brunchboy** [comment] 2016-02-06 22:14
Since Derek is so busy, I am trying to see if I can make any headway in understanding this issue, but it seems that I don’t know how to run a JavaFX based class. I tried just running `javac` on the sample @SMerrony provided, and it seems to compile fine, but when I try `java FXmidiTest1` I just get:

```
Error: Could not find or load main class FXmidiTest1
```

Can you point me in the right direction?

**Comment by SMerrony** [comment] 2016-02-07 08:23
Just comment out the first ('package') line and you should be good to go.

**Comment by brunchboy** [comment] 2016-02-07 21:16
Oh, yeah, that should have been obvious. You can tell it has been a few years since I used the actual Java language to build my code that runs in the JVM! I had assumed that `javac` would create package directories for me if it needed them.

Anyway, I am able to reproduce the hang, so when I have some time I can add more log statements to the native code to try and see exactly what is hanging and whether it is the attempt to get that lock that I suspect it is. Not that I am sure what I will do with that information, as I’m only superficially familiar with all the work Derek did on the native side, but it would be a start.

As a potential workaround for you in the mean time: I have discovered that running the `MidiSystem.getMidiDeviceInfo()` call on a separate thread avoids the deadlock:

``` java
public class FXmidiTest1 extends Application {

    @Override
    public void start(Stage primaryStage) {
        Button btn = new Button();
        btn.setText("Say 'Hello World'");
        btn.setOnAction( (ae) -> System.out.println("Hello World!") );

        StackPane root = new StackPane();
        root.getChildren().add(btn);

        new Thread() {
            public void run() {

                MidiDevice.Info[] infos = MidiSystem.getMidiDeviceInfo();
                System.out.println("Device info loaded: " + infos.length);
            }
        }.start();

        Scene scene = new Scene(root, 300, 250);       
        primaryStage.setTitle("Hello World!");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    } 
}
```

Running this renders the UI, and prints `Device info loaded: 18` on my system, and clicking the button prints `Hello World!`.

**Comment by brunchboy** [comment] 2017-05-13 04:59
It looks like a fix has been contributed in #18 and I am working on testing it!

**Comment by brunchboy** [comment] 2017-05-13 05:42
@SMerrony, would you be able to check if this pre-release version of CoreMidi4J fixes this issue for you too? (After unzipping it, because even though jar files are already zip files, GitHub made me run it through zip again… 🙄) Please see the next comment for an even more updated snapshot zip.

**Comment by brunchboy** [comment] 2017-05-13 22:19
Actually, here is an even better snapshot ZIP for you to try, which includes the fix for this issue, a fix for another sometimes-uninitialized variable in the native code, and a fix for an issue @DerekCook opened a while back about needing to call `System.exit()` in order to end your program. It also updates all the libraries we depend on. This is what we are going to actually release next if our testing goes well.

[coremidi4j-1.0-SNAPSHOT.jar.zip](https://github.com/DerekCook/CoreMidi4J/files/999074/coremidi4j-1.0-SNAPSHOT.jar.zip)

**Comment by DerekCook** [comment] 2017-05-14 11:09
Hi. Thanks James for going through this, and good work on that other elusive bug that we never found before.

I have tried the 1.0 snapshot with my an.factory librarian, and done some very quick SYSEX data transfer tests, and it looks fine on my system whilst the application is running in MyEclipse. 

I've got a band practice this afternoon, so need to pull up stumps now. I'll do a little more testing later, including building a standalone application version and trying that and also a MIDI keyboard via my application's general MIDI router, but looking good so far.

**Comment by brunchboy** [comment] 2017-05-14 16:38
That’s great! I have a release drafted, so as soon as you feel comfortable, it will just take a few minutes to update the version, build and upload a release artifact, tag the repository, and release it on GitHub and Maven Central. Then I can update my projects which depend on it to use this version. 👍

**Comment by brunchboy** [comment] 2017-05-14 17:23
All right, I have also updated the main project README to reflect that version 1.0 is out, and fix a couple of details (such as removing the `System.exit(0);` call from the code example), but I will not push that to GitHub until we do the actual release.

**Comment by DerekCook** [comment] 2017-05-14 18:18
All looking good this end. Let it rip.

This has been tested with an.factory rebuilt and installed as a new APP. I tested with SYSEX data transfers to/from my AN1x and my Focusrite Scarlett 2i4, and my Line6 MobileKeys25 sending note, mod wheel and pitch bend data to my AN1x via an.factory's MIDI Router. 

I tested on OS X 10.12.4 and Java 1.8.0_131

**Comment by brunchboy** [comment] 2017-05-14 20:31
All right, 1.0 here we go!

**Closed as completed** 2017-05-14 20:48 UTC
Labels: bug
